### ISSUE TITLE
Previews shows "No valid diagram found here!" all the time (startup issue)

### ISSUE THREAD

**Issue by huafu** [qjebbs/vscode-plantuml#140]
Here is what I found after some lookup in all logs (found in `Log (Window)`):
```
[2018-08-22 08:22:11.446] [renderer1] [error] Invalid arguments: Error: Invalid arguments
	at new e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:474:418)
	at Symbol.provideDocumentSymbols (/Users/huafu/.vscode/extensions/jkeys089.plantuml-1.8.1/out/src/symboler.js:46:90)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:732:493
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:110:323
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:84:776)
	at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:110:286)
	at e.provideDocumentSymbols (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:732:447)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:747:682
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:747:177)
	at e.$provideDocumentSymbols (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:747:644)
	at e._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:983)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:701)
	at e._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:767)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:536)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:669:452
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:672:575
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:96:903
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:713)
	at Socket._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:932)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

```bash
code --version
1.26.1
493869ee8e8a846b0855873886fc79d480d342de
x64
```

This happens on startupt of vscode, then any diagram shows "no valid diagram found here!" without generating any log anywhere

UPDATE: if it can help, the generate URL for current diagram does generate correct URL, but I guess it doesn't make use of the same stuff under the hood...

**Comment by huafu** [comment]
Sounds like you're using a deprecated API which might have gone away in latest vscode:
https://code.visualstudio.com/docs/extensionAPI/vscode-api#SymbolInformation

> deprecated - Please use the constructor taking a location object.

https://github.com/qjebbs/vscode-plantuml/blob/b4b29543ed9dbd00a9064a7456a654cf147418e4/src/providers/symboler.ts#L52-L57

**Comment by qjebbs** [comment]
Thanks for feedback.

Seems that you are using a very old fork of the extension, notice the latest is 2.8.5:

```
...
/Users/huafu/.vscode/extensions/jkeys089.plantuml-1.8.1
...
```

Regarding to deprecated API, I will look into it later when I have time.

**Comment by huafu** [comment]
but I've installed thru the vscode extension manager!

**Comment by huafu** [comment]
ooohhh, I was searching for `puml`, you should add it to the keywords. Because else only `NG PlantUML` is coming in

**Comment by qjebbs** [comment]
![image](https://user-images.githubusercontent.com/16953333/44447614-51b5d900-a61b-11e8-8107-94b466034671.png)

That fork (NG-Plantuml 1.8.1) is not published or maintained by me

**Comment by huafu** [comment]
yeah sorry, see my previous comment: https://github.com/qjebbs/vscode-plantuml/issues/140#issuecomment-414930889

**Comment by qjebbs** [comment]
Aha, you are welcome..

**Comment by huafu** [comment]
```diff
diff --git a/src/providers/symboler.ts b/src/providers/symboler.ts
index 8f77b9a..c510ea1 100644
--- a/src/providers/symboler.ts
+++ b/src/providers/symboler.ts
@@ -48,12 +48,13 @@ export class Symbol extends vscode.Disposable implements vscode.DocumentSymbolPr

         let diagrams = diagramsOf(document);
         for (let d of diagrams) {
+            const location = new vscode.Location(document.uri, new vscode.Range(d.start, d.end))
             results.push(
                 new vscode.SymbolInformation(
                     d.title,
                     vscode.SymbolKind.Object,
-                    new vscode.Range(d.start, d.end),
-                    document.uri, ""
+                    '',
+                    location
                 )
             );
         }
```

**Comment by huafu** [comment]
ah, nevermind, your plugin does work! Closing this issue, tho you definitely should add keywords so that your extension shows in the list when searching for `puml` ;-)

**Comment by mrseanryan** [comment]
just in case it helps anyone:

I had similar error, and it seems to be related to Visual Code's security that restricts using a non-https connection to plantUML.

steps:
- open a .plantUml file
- ALT + D -> error 'No valid diagram found here!'
- open an MD file that has some plantUML
- click 'open preview to the side'
- a grey button with text like 'content restricted' appears
- click -> allow insecure over http (IS remote?)
- the plantUML renders OK in the markdown preview
- go back to the .plantUml file
- ALT + D -> works!

- proper solution: setup a local plantUml server?

**Comment by seangwright** [comment]
@mrseanryan This is related to the Markdown security restrictions in VSCode

https://code.visualstudio.com/docs/languages/markdown#_markdown-preview-security

I have not found a way, as of yet, to set this setting via `settings.json` for the user or workspace.

**Comment by JekRock** [comment]
As mentioned [here](https://github.com/qjebbs/vscode-plantuml/issues/115#issuecomment-384874449), try to put the cursor somewhere between `@startuml` and `@enduml`, and then press `ALT + D` to open the preview. If the cursor is outside of the `@startuml @enduml` block, the "No valid diagrams found here!" error occurs.

**Comment by belfinwe** [comment]
@JekRock This solved my issue. Still a working solution!
Thanks 😃
