### ISSUE TITLE
TypeError: Cannot read property 'uri' of undefined when trying to Preview

### ISSUE THREAD

**Issue by zoulja** [qjebbs/vscode-plantuml#149]
Hello.
I installed this extension yesterday, played around for 2 hours, everything was just fine but suddenly I started to get the following error during Preview generation:

> TypeError: Cannot read property 'uri' of undefined
> 	at Config.jar (C:\Users\imbatman\.vscode\extensions\jebbs.plantuml-2.9.1\out\src\plantuml\config.js:24:62)
> 	at LocalRender.createTask (C:\Users\imbatman\.vscode\extensions\jebbs.plantuml-2.9.1\out\src\plantuml\renders\local.js:56:44)
> 	at LocalRender.render (C:\Users\imbatman\.vscode\extensions\jebbs.plantuml-2.9.1\out\src\plantuml\renders\local.js:46:21)
> 	at Object.exportDiagram (C:\Users\imbatman\.vscode\extensions\jebbs.plantuml-2.9.1\out\src\plantuml\exporter\exportDiagram.js:20:54)
> 	at Object.exportToBuffer (C:\Users\imbatman\.vscode\extensions\jebbs.plantuml-2.9.1\out\src\plantuml\exporter\exportToBuffer.js:13:28)
> 	at Previewer.<anonymous> (C:\Users\imbatman\.vscode\extensions\jebbs.plantuml-2.9.1\out\src\providers\previewer.js:161:41)
> 	at Generator.next (<anonymous>)
> 	at C:\Users\imbatman\.vscode\extensions\jebbs.plantuml-2.9.1\out\src\providers\previewer.js:7:71
> 	at new Promise (<anonymous>)
> 	at __awaiter (C:\Users\imbatman\.vscode\extensions\jebbs.plantuml-2.9.1\out\src\providers\previewer.js:3:12)
> 	at Previewer.doUpdate (C:\Users\imbatman\.vscode\extensions\jebbs.plantuml-2.9.1\out\src\providers\previewer.js:152:16)
> 	at Previewer.update (C:\Users\imbatman\.vscode\extensions\jebbs.plantuml-2.9.1\out\src\providers\previewer.js:131:18)
> 	at vscode.commands.registerCommand (C:\Users\imbatman\.vscode\extensions\jebbs.plantuml-2.9.1\out\src\providers\previewer.js:221:22)
> 	at e._executeContributedCommand (d:\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:726:706)
> 	at e.$executeContributedCommand (d:\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:727:212)
> 	at e._doInvokeHandler (d:\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:309)
> 	at e._invokeHandler (d:\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:27)
> 	at e._receiveRequest (d:\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:679:802)
> 	at e._receiveOneMessage (d:\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:678:993)
> 	at d:\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:791
> 	at d:\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:597
> 	at e.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
> 	at a (d:\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:787)
> 	at Socket._socketDataListener (d:\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:1006)
> 	at emitOne (events.js:116:13)
> 	at Socket.emit (events.js:211:7)
> 	at addChunk (_stream_readable.js:263:12)
> 	at readableAddChunk (_stream_readable.js:250:11)
> 	at Socket.Readable.push (_stream_readable.js:208:10)
> 	at Pipe.onread (net.js:594:20)
> 

Environment: Win7x64, VS Code 1.27.2
I have tried to reinstall everythin but still no luck

**Comment by xthunder81** [comment]
i have same error on ubuntu 18.04

**Comment by andyshid** [comment]
i have same error today.

**Comment by ugoigo** [comment]
i had same error when installed this plugin by yesterday, however it works fine under CLI.

**Comment by ouyangjia7** [comment]
I hava same problem on win today,
press alt + D and problem appeared.

**Comment by matthunt1984** [comment]
I have the same problem.
Installed VS Code, Java and Graphviz today just to get this work :/
Tried it at the command line and was able to generate a PNG for the same file

**Comment by v-odin** [comment]
Same issue on Ubuntu 16.04. Java and Graphiz are installed. 
Command line export works: `java -jar /usr/java/plantuml.jar --verbose test.plantuml`

**Comment by qjebbs** [comment]
Sorry, it should've fix with v2.9.2, please update.

**Comment by zoulja** [comment]
Yes, in my environment it's also fixed
