### ISSUE TITLE
Failed to preview/export diagrams in vscode (Error: write EPIPE)

### ISSUE THREAD

**Issue by kienct89** [qjebbs/vscode-plantuml#167]
VS Code version: 1.28.2
Plantuml plugin version: 2.9.8
Node.js version: 8.9.3

Detailed log:

```
Error: write EPIPE
at _errnoException (util.js:1024:11)
at Socket._writeGeneric (net.js:767:25)
at Socket._write (net.js:786:8)
at doWrite (_stream_writable.js:387:12)
at writeOrBuffer (_stream_writable.js:373:5)
at Socket.Writable.write (_stream_writable.js:290:11)
at Socket.write (net.js:704:40)
at pChain.then (C:\Users\user-1\.vscode\extensions\jebbs.plantuml-2.9.8\out\src\plantuml\renders\local.js:107:35)
at
```

Settings:

```json
{
    "plantuml.diagramsRoot": "docs/diagrams/src",
    "plantuml.exportOutDir": "docs/diagrams/out"
}
```

**Comment by kienct89** [comment]
I figured it out, the folder settings were incorrect

hope it helps someone

```
{
    "plantuml.diagramsRoot": "diagrams/src",
    "plantuml.exportOutDir": "diagrams/out"
}
```

**Comment by SSMM0498** [comment]
it does not work for me

**Comment by qjebbs** [comment]
@SSMM0498 `plantuml.diagramsRoot` and `plantuml.exportOutDir` should be YOUR path, and exists. Or just keep the default setting, it should work for most use case.

**Comment by kienct89** [comment]
I have to open the correct **folder** for it to work (one level above diagrams folder)

**Comment by aaronadamsTO** [comment]
> I figured it out, the folder settings were incorrect
> 
> hope it helps someone
> 
> ```
> {
>     "plantuml.diagramsRoot": "diagrams/src",
>     "plantuml.exportOutDir": "diagrams/out"
> }
> ```

It helped me, thank you @kienct89! This could probably use a better error message.

**Comment by sunilbato** [comment]
I am having following error can someone help 
Error found in diagram service- v1
java.lang.ClassNotFoundException: org.apache.batik.apps.rasterizer.SVGConverter
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:57)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:383)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:244)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:154)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:109)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:359)
	at net.sourceforge.plantuml.Run.main(Run.java:166)
Exception in thread "main" java.lang.UnsupportedOperationException
	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:76)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:383)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:244)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:154)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:109)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:359)
	at net.sourceforge.plantuml.Run.main(Run.java:166)

**Comment by vignif** [comment]
Solved it by installing java

```sudo apt install default-jre```

**Comment by ogaida** [comment]
i had the same problem on windows because i did not install plantuml itself. So the following cmd solved my problem:

run as admin:

```
choco install plantuml
```
