### ISSUE TITLE
Exporting PDF doesn't work

### ISSUE THREAD

**Issue by egekorkan** [qjebbs/vscode-plantuml#186]
I have tried exporting a plantuml file as pdf. I have tried multiple plantuml files and always get the same error:
```
java.lang.ClassNotFoundException: org.apache.batik.apps.rasterizer.SVGConverter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:57)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:362)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:223)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:154)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:100)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:354)
	at net.sourceforge.plantuml.Run.main(Run.java:167)
Exception in thread "main" java.lang.UnsupportedOperationException
	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:76)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:362)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:223)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:154)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:100)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:354)
	at net.sourceforge.plantuml.Run.main(Run.java:167)
```

I am guessing that the install doesn't install a necessary pdf converter library. Other formats including svg, eps and latex work.

**Comment by qjebbs** [comment]
Dependencies are to large to include, config `plantuml.jar` to use your own copy with dependencies. See also https://github.com/qjebbs/vscode-plantuml/issues/154

**Comment by egekorkan** [comment]
Thanks for clearing it up! Closing
