### ISSUE TITLE
Export Diagram from file fails

### ISSUE THREAD

**Issue by ziedbensalem** [qjebbs/vscode-plantuml#208]
vscode version: 1.30.2
plantuml extension version: 2.10.8

1)Export current diagram : diagram generated is incomplete

2)Export diragram from file:

TypeError: Cannot read property 'dir' of undefined
	at promises.push.diagrams.reduce (/Users/py07726/.vscode/extensions/jebbs.plantuml-2.10.8/out/src/plantuml/exporter/exportDiagrams.js:77:42)
	at Array.reduce (<anonymous>)
	at doExportsLimited (/Users/py07726/.vscode/extensions/jebbs.plantuml-2.10.8/out/src/plantuml/exporter/exportDiagrams.js:72:32)
	at Object.exportDiagrams (/Users/py07726/.vscode/extensions/jebbs.plantuml-2.10.8/out/src/plantuml/exporter/exportDiagrams.js:19:16)
	at Object.<anonymous> (/Users/py07726/.vscode/extensions/jebbs.plantuml-2.10.8/out/src/plantuml/exporter/exportDocument.js:56:26)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/py07726/.vscode/extensions/jebbs.plantuml-2.10.8/out/src/plantuml/exporter/exportDocument.js:4:58)
	at <anonymous>

**Comment by qjebbs** [comment]
Please tell the steps to reproduce.

**Comment by ziedbensalem** [comment]
- Env: VSCode Studio, long PUML file (296 lines)
1) RClick Mouse -> Select "Export Current Diagram", Select PNG format
=> PNG File successfully generated but, incomplete / truncated (at the last activities)
2) RClick Mouse -> Select "Export Diagram File"
=> Error Message:
TypeError: Cannot read property 'dir' of undefined
at promises.push.diagrams.reduce (/Users/py07726/.vscode/extensions/jebbs.plantuml-2.10.8/out/src/plantuml/exporter/exportDiagrams.js:77:42)
at Array.reduce ()
at doExportsLimited (/Users/py07726/.vscode/extensions/jebbs.plantuml-2.10.8/out/src/plantuml/exporter/exportDiagrams.js:72:32)
at Object.exportDiagrams (/Users/py07726/.vscode/extensions/jebbs.plantuml-2.10.8/out/src/plantuml/exporter/exportDiagrams.js:19:16)
at Object. (/Users/py07726/.vscode/extensions/jebbs.plantuml-2.10.8/out/src/plantuml/exporter/exportDocument.js:56:26)
at Generator.next ()
at fulfilled (/Users/py07726/.vscode/extensions/jebbs.plantuml-2.10.8/out/src/plantuml/exporter/exportDocument.js:4:58)
at

**Comment by ziedbensalem** [comment]
For issue:
1) RClick Mouse -> Select "Export Current Diagram", Select PNG format
=> PNG File successfully generated but, incomplete / truncated (at the last activities)

I confirm its because PUML Source Code file.
I removed some lines from source code, and the diagram was generated complete
It's a limit issue with PNG format Export.

**Comment by qjebbs** [comment]
I doubt that the issue is related to the specified diagram, does it work good for other diagrams, or the issue happens to every diagram in your environment?

**Comment by qjebbs** [comment]
If the issue only happens to a single diagram, I'm afraid you have to provide your source, but you may remove the sensitive data away.

**Comment by ziedbensalem** [comment]
I doubt that this issue is related to a single diagram.
It is an activity diagram, I tried to remove some random calls/lines and it was ok.
So I believe it's a problem of reached limit of the PNG size may be.

I cannot provide the Source Code diagram because it is confidential, and it depends on many libs.

**Comment by qjebbs** [comment]
can you provide the `some random calls/lines `?

**Comment by ziedbensalem** [comment]
pua -> pua : generate K-ID
    pua ->o pua_db : insert DB ......
    note left : pending_remove .........
      
    pua -> pauth : (REST) registration ....
          
    activate pauth
    pauth ->o pauth_db : insert ....
    pauth -> pauth : log insert ...

    pauth --> pua : (REST) r-registration....
    pua --> pib : (REST)r-create....
    note right of pib : This....

    pib -> kfa : (REST) Self_Registration ()

**Comment by qjebbs** [comment]
I guess this is the cause(http://plantuml.com/zh/faq):

> ## I want to generate huge diagrams!
> 
> PlantUML limits image width and height to 4096. There is a environment variable that you can set to override this limit: PLANTUML_LIMIT_SIZE. You have to define this variable before launching PlantUML, something like:
> 
> set PLANTUML_LIMIT_SIZE=8192
> or
> 
> setenv PLANTUML_LIMIT_SIZE 8192
> Another way is an option in the command line:
> 
> java -DPLANTUML_LIMIT_SIZE=8192 -jar /path/to/plantuml.jar ...
> Note that if you generate very big diagrams, (for example, something like 20 000 x 10 000 pixels), you can have some memory issues. The solution is to add this parameter to the java vm : -Xmx1024m.

See also `plantuml.commandArgs` of https://github.com/qjebbs/vscode-plantuml#extension-settings

**Comment by qjebbs** [comment]
Closing due to no activity...
