### ISSUE TITLE
PDF export fails on OSX

### ISSUE THREAD

**Issue by paustint** [qjebbs/vscode-plantuml#246]
I have been able to export to a PNG, but PDF is producing the following error:

example UML
```
@startuml Foo Onboarding
actor User as user
participant Website as web
database Database as db
actor Administrator as admin

group Initial Customer Account Request

  user -> web : User requests access to Foo
  web -> db : User record created
  web -> admin : Email notification sent to admin
  web -> user : User notified of pending account

  group Account approval

    admin -> web : Approves account in Foo
    web -> db : Database updated
    web -> user : User sent welcome email
    user -> web : User logs in
    web -> db : User email confirmed
    note over admin, user: When do we initiate a $0 contract? is this part of SOW, or something else?

  end

end

@enduml
```

```
Error found in diagram Foo Onboarding
java.lang.ClassNotFoundException: org.apache.batik.apps.rasterizer.SVGConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:57)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:337)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:198)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:154)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:110)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:359)
	at net.sourceforge.plantuml.Run.main(Run.java:166)
Exception in thread "main" java.lang.UnsupportedOperationException
	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:76)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:337)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:198)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:154)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:110)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:359)
	at net.sourceforge.plantuml.Run.main(Run.java:166)
```

**Comment by qjebbs** [comment]
Actually it fails on any OS, but it's not the extension to blame..

See more https://github.com/qjebbs/vscode-plantuml/issues?utf8=✓&q=is%3Aissue+is%3Aclosed+PDF
