### ISSUE TITLE
Markdown Preview Broken in v2.13.7

### ISSUE THREAD

**Issue by andrewthauer** [qjebbs/vscode-plantuml#311]
The v2.13.7 release seems to have broken markdown preview for any markdown files that contain plantuml code fences.

I think this may have been introduced in this commit (https://github.com/qjebbs/vscode-plantuml/commit/95c620522229fe108a1ba3680541d8167625e6f0).

Debugging the extensions indicates the following error:

```
rejected promise not handled within 1 second: TypeError: Cannot read property 'fsPath' of undefined
stack trace: TypeError: Cannot read property 'fsPath' of undefined
	at Object.getContentWithInclude (/path/to/vscode-plantuml/out/src/plantuml/diagram/include.js:15:33)
	at Diagram.get contentWithInclude [as contentWithInclude] (/path/to/vscode-plantuml/out/src/plantuml/diagram/diagram.js:78:82)
	at Object.makePlantumlURL (/path/to/vscode-plantuml/out/src/plantuml/plantumlURL.js:12:91)
	at /path/to/vscode-plantuml/out/src/plantuml/urlMaker/urlMaker.js:20:79
	at Array.map (<anonymous>)
	at Object.MakeDiagramURL (/path/to/vscode-plantuml/out/src/plantuml/urlMaker/urlMaker.js:20:52)
	at Object.renderHtml [as plantuml] (/path/to/vscode-plantuml/out/src/markdown-it-plantuml/render.js:17:29)
	at s.render (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:126178)
	at Object.render (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:86921)
	at async Object.provideTextDocumentContent (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:62698)
	at async p.doUpdate (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:75749)
```

**Comment by qjebbs** [comment]
This should be fixed with #310
