### ISSUE TITLE
Getting epipe error after update

### ISSUE THREAD

**Issue by Alex-Jongman** [qjebbs/vscode-plantuml#330]
I got an update message and in a hurry I accepted, but now I get an EPIPE error when I try to preview diagrams.
```
Error: write EPIPE
at afterWriteDispatched (internal/stream_base_commons.js:146:25)
at writeGeneric (internal/stream_base_commons.js:137:3)
at Socket._writeGeneric (net.js:698:11)
at Socket._write (net.js:710:8)
at doWrite (_stream_writable.js:418:12)
at writeOrBuffer (_stream_writable.js:402:5)
at Socket.Writable.write (_stream_writable.js:302:11)
at /home/alexjongman/.vscode/extensions/jebbs.plantuml-2.13.12/out/src/plantuml/renders/local.js:112:35
at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

Any suggestions on what to do? All I could find until now about this error was a reference to the diagrams root and export out dir setting. I've set them but to no effect on the error.

**Comment by qjebbs** [comment]
Sorry, I don't have enough info to reproduce this.

**Comment by furtivesock** [comment]
Not sure if this workaround will work for you too, but this is how I managed to fix this issue:
I installed the extension and got the same error. I installed PlantUML through Chocolatey, nothing changed. But after reopening VSCode preview works now.

**Comment by hendrickh** [comment]
Had the same issue - I've managed to resolve it by adding java to my path (C:\Program Files\Java\jdk1.8.0_221\bin). After restarting VSCode, it seems to be working fine.
Hope this helps!

**Comment by Vivraan** [comment]
Yeah, none of that helps. Bumping up issue - please fix!

**Comment by smye** [comment]
> Had the same issue - I've managed to resolve it by adding java to my path (C:\Program Files\Java\jdk1.8.0_221\bin). After restarting VSCode, it seems to be working fine.
> Hope this helps!

Thanks a lot!

**Comment by vab2048** [comment]
Can confirm I had the same issue and by adding java to the path (java 11 on windows 10) it started working.
