### ISSUE TITLE
Java heap space out of memory

### ISSUE THREAD

**Issue by mturconi78** [qjebbs/vscode-plantuml#345]
I used the plantuml without any issue in most of my diagrams, but with a particular diagram I have this issue.
I'm trying to export the flow in PDF.
Version used v2.13.13 and FOP and Batik installed as described in https://plantuml.com/pdf

Have you already see it? If you need I can try to send you the diagram.

Error found in diagram Base
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:73)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:333)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:185)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:140)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:156)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:113)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:363)
	at net.sourceforge.plantuml.Run.main(Run.java:170)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.awt.image.SinglePixelPackedSampleModel.createDataBuffer(Unknown Source)
	at java.awt.image.Raster.createWritableRaster(Unknown Source)
	at java.awt.image.BufferedImage.getData(Unknown Source)
	at org.apache.xmlgraphics.ps.ImageEncodingHelper.encodeRenderedImageAsRGB(ImageEncodingHelper.java:124)
	at org.apache.xmlgraphics.ps.ImageEncodingHelper.writeRGBTo(ImageEncodingHelper.java:113)
	at org.apache.xmlgraphics.ps.ImageEncodingHelper.encode(ImageEncodingHelper.java:317)
	at org.apache.fop.render.pdf.ImageRenderedAdapter.outputContents(ImageRenderedAdapter.java:215)
	at org.apache.fop.pdf.PDFImageXObject.outputRawStreamData(PDFImageXObject.java:145)
	at org.apache.fop.pdf.AbstractPDFStream.encodeAndWriteStream(AbstractPDFStream.java:165)
	at org.apache.fop.pdf.AbstractPDFStream.output(AbstractPDFStream.java:209)
	at org.apache.fop.pdf.PDFImageXObject.output(PDFImageXObject.java:65)
	at org.apache.fop.pdf.PDFDocument.output(PDFDocument.java:944)
	at org.apache.fop.svg.PDFGraphics2D.flushPDFDocument(PDFGraphics2D.java:451)
	at org.apache.fop.svg.PDFGraphics2D.addRenderedImage(PDFGraphics2D.java:1265)
	at org.apache.fop.svg.PDFGraphics2D.drawImage(PDFGraphics2D.java:535)
	at org.apache.fop.svg.PDFGraphics2D.drawImage(PDFGraphics2D.java:494)
	at org.apache.batik.ext.awt.image.GraphicsUtil.drawImage(Unknown Source)
	at org.apache.batik.ext.awt.image.GraphicsUtil.drawImage(Unknown Source)
	at org.apache.batik.ext.awt.image.renderable.PadRable8Bit.paintRable(Unknown Source)
	at org.apache.batik.ext.awt.image.GraphicsUtil.drawImage(Unknown Source)
	at org.apache.batik.ext.awt.image.renderable.PadRable8Bit.paintRable(Unknown Source)
	at org.apache.batik.ext.awt.image.GraphicsUtil.drawImage(Unknown Source)
	at org.apache.batik.ext.awt.image.renderable.FilterChainRable8Bit.paintRable(Unknown Source)
	at org.apache.batik.ext.awt.image.GraphicsUtil.drawImage(Unknown Source)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(Unknown Source)
	at org.apache.batik.gvt.ShapeNode.paint(Unknown Source)
	at org.apache.batik.gvt.CompositeGraphicsNode.primitivePaint(Unknown Source)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(Unknown Source)
	at org.apache.batik.gvt.CompositeGraphicsNode.primitivePaint(Unknown Source)
	at org.apache.batik.gvt.CanvasGraphicsNode.primitivePaint(Unknown Source)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(Unknown Source)
Exception in thread "main" java.lang.UnsupportedOperationException
	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:76)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:333)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:185)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:140)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:156)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:113)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:363)
	at net.sourceforge.plantuml.Run.main(Run.java:170)

**Comment by qjebbs** [comment]
#154
