### ISSUE TITLE
Cannot export diagrams to pdf

### ISSUE THREAD

**Issue by Mavv3006** [qjebbs/vscode-plantuml#392]
whenever I try to export a diagram like 

```plantuml
@startuml
user --> (usecase)
@enduml
```

to pdf I get the following error message in the output: 

```
Error found in diagram text
java.lang.ClassNotFoundException: org.apache.batik.apps.rasterizer.SVGConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:57)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:328)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:172)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:140)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:160)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:113)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:375)
	at net.sourceforge.plantuml.Run.main(Run.java:176)
Exception in thread "main" java.lang.UnsupportedOperationException
	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:76)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:328)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:172)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:140)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:160)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:113)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:375)
	at net.sourceforge.plantuml.Run.main(Run.java:176)
```

**Comment by qjebbs** [comment]
#154
