### ISSUE TITLE
Preview fails with 301 error

### ISSUE THREAD

**Issue by dveluchamy** [qjebbs/vscode-plantuml#439]
VS Code: 1.60.0
![image](https://user-images.githubusercontent.com/26489766/133123668-e1e47f4d-4a73-4acb-942f-4590c7e9123c.png)
Extension ID: jebbs.plantuml
Export Format: SVG
Preview error:
![image](https://user-images.githubusercontent.com/26489766/133123837-dd2a9b74-6738-48fd-8ec4-30e69730d2f3.png)

OUTPUT:
Error: 301 Moved Permanently

GET https://plantuml.com/plantuml/svg/0/...
	at ClientRequest.closeCallback (c:\Users\dveluchamy\.vscode\extensions\jebbs.plantuml-2.15.1\out\src\plantuml\renders\httpWrapper.js:77:27)
	at ClientRequest.emit (events.js:315:20)
	at TLSSocket.socketCloseListener (_http_client.js:428:9)
	at TLSSocket.emit (events.js:327:22)
	at net.js:673:12
	at TCP.done (_tls_wrap.js:563:7)

**Comment by qjebbs** [comment]
It's user's responsibility to pick or setup an available plantuml server for the extension.
