### ISSUE TITLE
"Error: certificate has expired"  to preview or export

### ISSUE THREAD

**Issue by MitamuFuru** [qjebbs/vscode-plantuml#445]
Hello.
When I try to preview or export diagram (rendering by  PlantUMLServer),
I get Error: certificate has expired(see below).
Does anyone know the cause?

```
Error: certificate has expired
at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
at TLSSocket.emit (events.js:315:20)
at TLSSocket._finishInit (_tls_wrap.js:932:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
```
### Environment details:
OS: macOS 11.5.2
Vscode: v1.60.2
Plantuml extension: v2.15.1
Reder: PlantUMLServer
Server: https://www.plantuml.com/plantuml

**Comment by jsnape** [comment]
It may be related to the Let's Encrypt root CA expiring. I just came here to see if this extension uses OpenSSL 1.0.2 or earlier: https://scotthelme.co.uk/lets-encrypt-old-root-expiration/

**Comment by cmdkeen** [comment]
We're also experiencing this, the PlantUML server we're running works fine but the VS Code extension refuses to work

**Comment by MitamuFuru** [comment]
@jsnape 
So that's it.
Thank you for providing useful information.

@cmdkeen 
Does that mean that the only way left is to use LOCAL render(=graphviz )?

**Comment by cmdkeen** [comment]
@MitamuFuru our manual workaround is to go to the server URL and paste in the PlantUML and it renders there fine. The VS code integration for preview and exporting is broken (the syntax highlighting, templates etc all still work).

**Comment by cmdkeen** [comment]
It sounds like this is a VS Code level issue rather than anything in the extension https://github.com/microsoft/vscode/issues/134244

**Comment by MitamuFuru** [comment]
@cmdkeen 
OMG(T T);
I'll do it that "Copy & Paste" way.  
thank you.

**Comment by MitamuFuru** [comment]
After changing the render setting to "LOCAL", the diagram was output(preview) normally.

**Comment by danbrakeley** [comment]
I changed my settings to use `http` instead of `https`, and it works again, but is no longer secure.
