### ISSUE TITLE
[renderer1] [error] spawn java ENOENT: Error: spawn java ENOENT

### ISSUE THREAD

**Issue by majeric** [qjebbs/vscode-plantuml#460]
Mac Monterey 12.0.1
VS Code 1.63.0
PlantUML v2.16.1

[2021-12-11 17:52:42.110] [renderer1] [error] spawn java ENOENT: Error: spawn java ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
	at onErrorNT (internal/child_process.js:465:16)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by JiHaoChina** [comment]
The reason is that it's running needs java environment. You should install java SDK in your computer.

**Comment by jnz86** [comment]
Just a head's up to anyone that may ever have the same thing...

If you're using VS Code remote dev containers... You need Java/JRE the container, OR, you need to open your PlantUML file as a local. 

Can't open the puml "remotely" and using local JRE. It's both remote or both local.

**Comment by Bernardoow** [comment]
> I had the same issue. You just need to install the JRE for your OS.

I had the same issue and then following the instruction I installed using the command `sudo apt install default-jre` and issue was resolved.
