### ISSUE TITLE
On preview a certificate error occurs - see issue #445

### ISSUE THREAD

**Issue by marvin-littlewood** [qjebbs/vscode-plantuml#474]
Thank you for your help.

Environment:
Plant UML: 2.17.2

VSCode:
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

The following appears when I try to preview an activity diagram, on Windows 10 I get the following:

Error: certificate has expired
at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
at TLSSocket.emit (events.js:315:20)
at TLSSocket.EventEmitter.emit (domain.js:467:12)
at TLSSocket._finishInit (_tls_wrap.js:932:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)

Yet on MacOS, there is no problem with the same plant UML text.

**Comment by Aviortheking** [comment]
same error on VSCodium 1 .63.2

PlantUML v2.17.2

```
Error: certificate has expired
at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
at TLSSocket.emit (events.js:315:20)
at TLSSocket._finishInit (_tls_wrap.js:932:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
```

settings
![image](https://user-images.githubusercontent.com/15822031/152997567-0d999fca-b1cd-45ad-ad24-ef30b7c4c51b.png)

Example uml (happens with any UML)
```
@startuml

class Test {
	String Pouet
}

@enduml
```

**Comment by pommetjehorlepiep** [comment]
Got same exception, just different error but still certificate related.

Running PlantUML Picoweb behind a reverse proxy using https.
VSCode: 1.66.2
PlantUML extension: v2.17.2
PlantUML version: 1.2022.4

![image](https://user-images.githubusercontent.com/8982487/166170746-5d923f62-b533-4836-905b-2748aabbb9cb.png)

But over http it works fine:
![image](https://user-images.githubusercontent.com/8982487/166170922-e52800cc-ed82-43b5-9554-80adee046437.png)
