### ISSUE TITLE
Preview broken outside of folder (TypeError: Cannot read properties of undefined (reading 'uri') )

### ISSUE THREAD

**Issue by mawid6** [qjebbs/vscode-plantuml#495]
Hi! 
_Recently:ish I have been getting this error alot. When I try to preview something unsaved and for alot of different files._

_I am not sure what the problem might be. **Any tips / ideas?**_

# Preview seems to not work with files with no folder/workspace
I have been playing around trying to get some consistent repro, and it seems that 
* **anytime I try to preview a file** that I have just opened "solo" - i e **not within a folder or project**, I get this error. 
* Also happens if I have a project / folder open and open/drag a file into vs code that is not within the opened project/folder.
* There is no connection to the diagram source itself, this issue is caused by "setup factors".

Happens for the simplest of tests, e g 
```
@startuml
a -> b: msg
@enduml
```

Error:

```
TypeError: Cannot read properties of undefined (reading 'uri')
	at c:\Users\mawid6\.vscode\extensions\jebbs.plantuml-2.17.2\out\src\plantuml\renders\local.js:85:47
	at Array.reduce (<anonymous>)
	at LocalRender.createTask (c:\Users\mawid6\.vscode\extensions\jebbs.plantuml-2.17.2\out\src\plantuml\renders\local.js:65:56)
	at LocalRender.render (c:\Users\mawid6\.vscode\extensions\jebbs.plantuml-2.17.2\out\src\plantuml\renders\local.js:47:21)
	at Object.exportDiagram (c:\Users\mawid6\.vscode\extensions\jebbs.plantuml-2.17.2\out\src\plantuml\exporter\exportDiagram.js:20:71)
	at Object.exportToBuffer (c:\Users\mawid6\.vscode\extensions\jebbs.plantuml-2.17.2\out\src\plantuml\exporter\exportToBuffer.js:13:28)
	at Previewer.<anonymous> (c:\Users\mawid6\.vscode\extensions\jebbs.plantuml-2.17.2\out\src\providers\previewer.js:149:41)
	at Generator.next (<anonymous>)
	at c:\Users\mawid6\.vscode\extensions\jebbs.plantuml-2.17.2\out\src\providers\previewer.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\mawid6\.vscode\extensions\jebbs.plantuml-2.17.2\out\src\providers\previewer.js:4:12)
	at Previewer.doUpdate (c:\Users\mawid6\.vscode\extensions\jebbs.plantuml-2.17.2\out\src\providers\previewer.js:140:16)
	at Previewer.<anonymous> (c:\Users\mawid6\.vscode\extensions\jebbs.plantuml-2.17.2\out\src\providers\previewer.js:101:18)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\mawid6\.vscode\extensions\jebbs.plantuml-2.17.2\out\src\providers\previewer.js:5:58)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

-----
#### Update
I have not played around extensively with this error, but it is still there. 

Similar (fixed) issue: #149. 
Seems to be similar issues for other vs code plugins (example: [cpptools](https://github.com/microsoft/vscode-cpptools/issues/8280) ), again, I have not investigated.

**Comment by AcccGO** [comment]
TypeError: Cannot read properties of undefined (reading 'uri')
I also have this problem  in 2.18 extension in vscode when i open a new created simple  .pu file
