### ISSUE TITLE
OpenJDK can not convert photo to pdf

### ISSUE THREAD

**Issue by RickyLiu0w0** [qjebbs/vscode-plantuml#524]
Hello:

When I convert photo to pdf, it throws an error:

```java
java.lang.ClassNotFoundException: org.apache.batik.apps.rasterizer.SVGConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:59)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:277)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:132)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:178)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:172)
	at net.sourceforge.plantuml.Pipe.generateDiagram(Pipe.java:100)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:92)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:354)
	at net.sourceforge.plantuml.Run.main(Run.java:181)
Exception in thread "main" java.lang.UnsupportedOperationException
	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:78)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:277)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:132)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:178)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:172)
	at net.sourceforge.plantuml.Pipe.generateDiagram(Pipe.java:100)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:92)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:354)
	at net.sourceforge.plantuml.Run.main(Run.java:181)
```

I use the jave version:

```bash
openjdk 11.0.15 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)
```

**Comment by RickyLiu0w0** [comment]
The problem is the same as #186

Issue closed.
