### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'fsPath')

### ISSUE THREAD

**Issue by Abdelkrim** [qjebbs/vscode-plantuml#533]
**PlantUML export:  Current file diagram** produces the following error

**version:** 2.17.5
```
TypeError: Cannot read properties of undefined (reading 'fsPath')
	at calculateExportPath (c:\Users\abdel\.vscode\extensions\jebbs.plantuml-2.17.5\out\src\plantuml\tools.js:107:68)
	at c:\Users\abdel\.vscode\extensions\jebbs.plantuml-2.17.5\out\src\plantuml\exporter\exportDiagrams.js:83:60
	at Array.reduce (<anonymous>)
	at doExportsLimited (c:\Users\abdel\.vscode\extensions\jebbs.plantuml-2.17.5\out\src\plantuml\exporter\exportDiagrams.js:76:32)
	at exportDiagrams (c:\Users\abdel\.vscode\extensions\jebbs.plantuml-2.17.5\out\src\plantuml\exporter\exportDiagrams.js:23:16)
	at c:\Users\abdel\.vscode\extensions\jebbs.plantuml-2.17.5\out\src\plantuml\exporter\exportDocument.js:58:45
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\abdel\.vscode\extensions\jebbs.plantuml-2.17.5\out\src\plantuml\exporter\exportDocument.js:5:58)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by nsk7even** [comment]
This has to do something with file path settings. After changing my file organisation I encountered this issue also. Didn't identified the exact cause, but re-enabling the option `Export Include Folder Heirarchy` solved it for me:
![grafik](https://github.com/qjebbs/vscode-plantuml/assets/6367390/85a1656b-032b-4e24-9c80-9b755928b1ef)

Not sure this is the solution for you also. You may check the settings file directly for any modified options of plantuml and comment them out.
