### ISSUE TITLE
Error: 414 URI Too Long

### ISSUE THREAD

**Issue by werwolfby** [qjebbs/vscode-plantuml#578]
When working over local render server I starts to get 414, the same docker container worked before the update.

**Comment by JohnLeyva** [comment]
my renderer is also located in locahost

Wondering if it is possible to use POST instead of GET



Error: 414 URI Too Long

GET http://localhost:8080/svg/0/...
at ClientRequest.closeCallback (c:\Users\XXXXXX\.vscode\extensions\jebbs.plantuml-2.18.1\out\src\plantuml\renders\httpWrapper.js:78:27)
at ClientRequest.emit (node:events:514:28)
at Socket.socketCloseListener (node:_http_client:464:9)
at Socket.emit (node:events:526:35)
at TCP. (node:net:323:12)

**Comment by werwolfby** [comment]
I've installed plantuml locally to mitigate the issue for now.

**Comment by JohnLeyva** [comment]
Another workaround

Add to C:\Windows\System32\drivers\etc\hosts

127.0.0.1 plantuml.local

In settings use  http://plantuml.local:8080

**Comment by werwolfby** [comment]
You mean that issue is only for localhost? Then I can just use docker host name.

**Comment by AntonMartynenko-GitHub** [comment]
FIghting with the same problem in `Version 2.18.1`.

The first time I used render, it worked. But the second time, when I opened the code, the diagram did not render and threw an error.

```
Error: 414 URI Too Long

GET http://localhost:10000/svg/0/...
at ClientRequest.closeCallback (c:\Users\enono\.vscode\extensions\jebbs.plantuml-2.18.1\out\src\plantuml\renders\httpWrapper.js:78:27)
at ClientRequest.emit (node:events:518:28)
at ClientRequest.emit (node:domain:489:12)
at Socket.socketCloseListener (node:_http_client:467:9)
at Socket.emit (node:events:530:35)
at Socket.emit (node:domain:489:12)
at TCP. (node:net:343:12)
```

If I reopen VS Code, the diagram renders again, and the story repeats. 

I use Docker and the `plantuml-server:jetty` image.

## The plausible cause

I tried to revert the version of extension to `Version 2.17.6`, and now it's working perfectly. 

The problem starts in `Version 2.18.0` and still persists in `Version 2.18.1`.

**Comment by hwang63130** [comment]
@JohnLeyva 
the hosts file method does not work for me. 

@AntonMartynenko-GitHub 
reverting to 2.17.6 solved my problem as well. 

I guess I will stick with 2.17.6 for now.
