### ISSUE TITLE
AWSPuml Entity objects will not generate a preview (produces an error)

### ISSUE THREAD

**Issue by cfGenesys** [qjebbs/vscode-plantuml#583]
Attempting to run https://github.com/awslabs/aws-icons-for-plantuml?tab=readme-ov-file#hello-world the following error below is produced. The error seems to relate to using the entity instead of the participant; that is if WorkDocs, and SimpleStorageService are change to WorkDocsParticipant and SimpleStorageServiceParticipant the plugin will generate a preview. Others seem to be having a similar issue: https://github.com/awslabs/aws-icons-for-plantuml/issues/66.
I was able to use the hello-world in both the plantUML online server and the installed version with now issue.

`Error found in diagram Hello World
java.io.IOException: Cannot run program "/opt/local/bin/dot": error=2, No such file or directory
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
at java.base/java.lang.Runtime.exec(Runtime.java:594)
at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:164)
at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:124)
at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:81)
Caused by: java.io.IOException: error=2, No such file or directory
at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
at java.base/java.lang.ProcessImpl.(ProcessImpl.java:314)
at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
... 5 more
java.io.IOException: Cannot run program "/opt/local/bin/dot": error=2, No such file or directory
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
at java.base/java.lang.Runtime.exec(Runtime.java:594)
at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:164)
at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:124)
at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:81)
Caused by: java.io.IOException: error=2, No such file or directory
at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
at java.base/java.lang.ProcessImpl.(ProcessImpl.java:314)
at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
... 5 more

`

**Comment by The-Lum** [comment]
Hi @cfGenesys, and all,

- Is `dot` is installed on your system?
- Could you test the same example but without `dot` GraphViz?

```puml
@startuml Hello World
!pragma layout smetana

' Uncomment the line below for "dark mode" styling
'!$AWS_DARK = true

!include <awslib/AWSCommon.puml>
!include <awslib/BusinessApplications/all.puml>
!include <awslib/Storage/SimpleStorageService.puml>

actor "Person" as personAlias
WorkDocs(desktopAlias, "Label", "Technology", "Optional Description")
SimpleStorageService(storageAlias, "Label", "Technology", "Optional Description")

personAlias --> desktopAlias
desktopAlias --> storageAlias

@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/dL5DRzD04BtlhvXOI4cbE0PkL53L94L415h5HUM6nlOaNcMykzfPKwM_dd7QGoJWmcddxNoyDs-k9M5CGy_mcPWzFFZ8hPc4YFiUWV7eXmJIKqA7naoNFXoZtNS9thv-ymxA7f-yMpI-dyFQDGlm4MmImDtEiiL4ie2I6RPZYy2MXE8lQXTcMjsjVkGRsv0JojSjkMHtbk8bV5tVm-oJpccLqxBCGOYWIod8PL7iRUg6UYGiy54OQndVt3RUIRxpCG-CRbodgDdNHO-IA1QRzVBcMtLpeGl0TwVDlV91wWZOEeAQs3-2TaFMOZn0xrlAGD9HitipdRmg7wgVgtBx1Jv0YWCPOoRMDJoq1Ez76ROkj6IfSzMCeEnNVnPy74IvHCeGs3QOh2ekaFbVzLNoUWCgAji7fXTKgNtgsKkFmIQDekyeYdSPe40uXQLwBqPFULZvHcOjoI7vSFgTGxP1NJZJu9wQpdds--E8RiEe2HbM94sq9vHTcB_np-GP_jz4SoOIylmAplMPSt3AddCPSqskrUL_0m00)](https://www.planttext.com/?text=dL5DRzD04BtlhvXOI4cbE0PkL53L94L415h5HUM6nlOaNcMykzfPKwM_dd7QGoJWmcddxNoyDs-k9M5CGy_mcPWzFFZ8hPc4YFiUWV7eXmJIKqA7naoNFXoZtNS9thv-ymxA7f-yMpI-dyFQDGlm4MmImDtEiiL4ie2I6RPZYy2MXE8lQXTcMjsjVkGRsv0JojSjkMHtbk8bV5tVm-oJpccLqxBCGOYWIod8PL7iRUg6UYGiy54OQndVt3RUIRxpCG-CRbodgDdNHO-IA1QRzVBcMtLpeGl0TwVDlV91wWZOEeAQs3-2TaFMOZn0xrlAGD9HitipdRmg7wgVgtBx1Jv0YWCPOoRMDJoq1Ez76ROkj6IfSzMCeEnNVnPy74IvHCeGs3QOh2ekaFbVzLNoUWCgAji7fXTKgNtgsKkFmIQDekyeYdSPe40uXQLwBqPFULZvHcOjoI7vSFgTGxP1NJZJu9wQpdds--E8RiEe2HbM94sq9vHTcB_np-GP_jz4SoOIylmAplMPSt3AddCPSqskrUL_0m00) 

_If that can help,_
Regards,
Th.
