### ISSUE TITLE
Relative path cannot be used for -config option because -Duser.dir is no longer set

### ISSUE THREAD

**Issue by skystar0227** [qjebbs/vscode-plantuml#586]
Thank you for this greate extension.

According to the following comment, relative path can be specified for -config thanks to -Duser.dir.

https://github.com/qjebbs/vscode-plantuml/issues/152#issuecomment-428479976

However, this won't work currently.
I think becaluse the following update removed the code which set -Duser.dir.

https://github.com/qjebbs/vscode-plantuml/commit/3a4d003be1f2c00dafe68ea04009827974b05bb5

Could you please restore the code so that relative path for -config get working?

**Comment by scalarion** [comment]
I have the same problem:

    "plantuml.jarArgs": [
        "-config",
        "<absolute path to file>/plantuml.iuml",
        "-Playout=smetana",
    ],

works but

    "plantuml.jarArgs": [
        "-config",
        "plantuml.iuml",
        "-Playout=smetana",
    ],

brings following exception:

Exception in thread "main" java.io.FileNotFoundException: plantuml.iuml (No such file or directory)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
at java.base/java.io.FileInputStream.(FileInputStream.java:152)
at java.base/java.io.FileInputStream.(FileInputStream.java:106)
at java.base/java.io.FileReader.(FileReader.java:60)
at net.sourceforge.plantuml.Option.initConfig(Option.java:575)
at net.sourceforge.plantuml.Option.(Option.java:324)
at net.sourceforge.plantuml.Run.main(Run.java:131)

In use a settings.json in my workspace folder
