### ISSUE TITLE
Exceptions dring export with color gradients

### ISSUE THREAD

**Issue by DRESAAN** [qjebbs/vscode-plantuml#64]
My style contains some color gradients as background colors. When I try to export it as pdf or latex it throws the following exception.
The export as png does work correctly. Also the pdf/latex export works if I change the color to a solid color.
My example code ist also listed below.

Examplecode:
`
skinparam class {
    BackgroundColor #c3d8f4-#6192d1
    BorderColor   #505050
    FontColor  #505050
}
class Class{ Dummy }
`

Exception:
`java.lang.ClassCastException: net.sourceforge.plantuml.graphic.HtmlColorGradient cannot be cast to net.sourceforge.plantuml.graphic.HtmlColorSimple
	at net.sourceforge.plantuml.ugraphic.ColorMapperIdentity.getMappedColor(ColorMapperIdentity.java:58)
	at net.sourceforge.plantuml.ugraphic.ColorMapperTransparentWrapper.getMappedColor(ColorMapperTransparentWrapper.java:61)
	at net.sourceforge.plantuml.ugraphic.tikz.DriverRectangleTikz.draw(DriverRectangleTikz.java:54)
	at net.sourceforge.plantuml.ugraphic.tikz.DriverRectangleTikz.draw(DriverRectangleTikz.java:45)
	at net.sourceforge.plantuml.ugraphic.AbstractUGraphic.draw(AbstractUGraphic.java:89)
	at net.sourceforge.plantuml.svek.image.EntityImageClass.drawInternal(EntityImageClass.java:159)
	at net.sourceforge.plantuml.svek.image.EntityImageClass.drawU(EntityImageClass.java:128)
	at net.sourceforge.plantuml.svek.SvekResult.drawU(SvekResult.java:83)
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageInternal(ImageBuilder.java:248)
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageTOBEMOVED(ImageBuilder.java:172)
	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:124)
	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:70)
	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:339)
	at net.sourceforge.plantuml.classdiagram.ClassDiagram.exportDiagramInternal(ClassDiagram.java:207)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:236)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:134)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:154)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:95)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:285)
	at net.sourceforge.plantuml.Run.main(Run.java:136)`

**Comment by qjebbs** [comment]
The problem is not about the plugin, but maybe about the plantuml.jar. If you use customize jar, consider updating it to latest. If the error continues, I suggest you feedback to author of plantuml.

In my enviroment, it works fine.

**Comment by qjebbs** [comment]
Sorry, I missed the part you said "png" renders correctly. PlantUML doesn't support PDF very well, as tried a bit in the past, I encountered many other errors besides yours. 

And again, it's beyond the plugin implement, you should turn to PlantUML author for help, or give up the try of PDF.

**Comment by DRESAAN** [comment]
Thank you for your quick response. I reposted the problem on the PlantUML site.
For everbody who is interested the post might be found here: [PlantUML](http://plantuml.sourceforge.net/qa/?qa=6481/exceptions-during-export-with-color-gradients) (after the question was accepted)
