### ISSUE TITLE
Path must be a string. Received [Function]: TypeError: Path must be a string.

### ISSUE THREAD

**Issue by c835722** [qjebbs/vscode-plantuml#74]
**Observation:**
Cannot preview current diagram.puml

**Version:**
ProductName: Mac OS X
ProductVersion: 10.13
BuildVersion:	17A405
vs-code-insiders v.18 2017-10-24.
jebbs.plantuml-2.3.2
No vscode settings override.

**Steps to reproduce:**
Preview current UML diagram

**Log snippet:**
```
shell.ts:454 Path must be a string. Received [Function]: TypeError: Path must be a string. Received [Function]
	at assertPath (path.js:7:11)
	at Object.isAbsolute (path.js:1200:5)
	at Includer._calcIncludes (/Users/foobar/.vscode-insiders/extensions/jebbs.plantuml-2.3.2/out/src/plantuml/diagram/includer.js:24:23)
	at Includer.addIncludes (/Users/foobar/.vscode-insiders/extensions/jebbs.plantuml-2.3.2/out/src/plantuml/diagram/includer.js:11:18)
	at DiagramAt (/Users/foobar/.vscode-insiders/extensions/jebbs.plantuml-2.3.2/out/src/plantuml/diagram/diagram.js:92:48)
	at Diagrams.AddDocument (/Users/foobar/.vscode-insiders/extensions/jebbs.plantuml-2.3.2/out/src/plantuml/diagram/diagram.js:30:39)
	at Symbol.provideDocumentSymbols (/Users/foobar/.vscode-insiders/extensions/jebbs.plantuml-2.3.2/out/src/providers/symboler.js:43:43)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:431342
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:92454
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:72219)
	at Object.t.asWinJsPromise (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:92417)
	at e.provideDocumentSymbols (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:431296)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:443135
	at e._withAdapter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:442774)
	at e.$provideDocumentSymbols (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:443097)
	at t.e.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:506491)
	at e._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:353452)
	at e._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:353142)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:352169
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354088
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:84834
	at e.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:84117)
```

**Comment by qjebbs** [comment]
duplicated with https://github.com/qjebbs/vscode-plantuml/issues/68. But I will try to reproduce with vs-code-insiders.

**Comment by qjebbs** [comment]
Tried in win7+insider, still can't reproduce.

**Comment by qjebbs** [comment]
If you can debug in your environment, fix and start a PR would be appreciated!

**Comment by c835722** [comment]
Disable Spellcheck plugin and retry. See further updated on #68 .

**Comment by qjebbs** [comment]
Next version of the plugin should work with Spellcheck plugin without error. Please update.
